galaxy_info:
  author: Saad_khan
  description: A role to install and configure Apache web server
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - web
    - apache
    - server

dependencies: []
